{
 "title": "Azure Monitor for Containers - Geneva Logs Multitenacy- Platform",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"cadvisor\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fluent-bit input records/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_input_records_total{cluster=~\"$cluster\", name=~\"$namespace-*\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Fluent-bit output process records/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\", name=~\"$namespace-*\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Fluent-bit output process records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\", name=~\"$namespace-*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_records_total{cluster=~\"$cluster\", name=~\"$namespace-*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input bytes/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_bytes_total{cluster=~\"$cluster\", name=~\"$namespace-*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output process bytes/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_proc_bytes_total{cluster=~\"$cluster\", name=~\"$namespace-*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input bytes/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_input_bytes_total{cluster=~\"$cluster\", name=~\"$namespace-*\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Fluent-bit output process bytes/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_output_proc_bytes_total{cluster=~\"$cluster\", name=~\"$namespace-*\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Fluent-bit retries/fails",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "\r\nsum by (node) (rate(fluentbit_output_retries_failed_total{cluster=~\"$cluster\", name=~\"$namespace-*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output dropped records/s",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_dropped_records_total{cluster=~\"$cluster\", name=~\"$namespace-*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output errors/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_errors_total{cluster=~\"$cluster\", name=~\"$namespace-*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}