{
 "title": "Azure Monitor for Containers",
 "description": "Azure Monitor for Containers Container Log Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\"})"
    }
   ]
  },
  {
   "title": "Fluent-bit input records/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_input_records_total{name=\"oms_tail\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit output process records/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_proc_records_total{name=\"oms_output\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fluent-bit input bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_input_bytes_total{name=\"oms_tail\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit output bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_proc_bytes_total{name=\"oms_output\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fluent-bit output dropped records/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 21 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_dropped_records_total{name=\"oms_output\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fluent-bit retries/fails",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_retries_failed_total{name=\"oms_output\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit error/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 2, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_errors_total{name=\"oms_output\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}