{
 "title": "Azure Monitor for Containers (1P) Service",
 "description": "Azure Monitor for Containers - Service - 1P",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "(App) Fluent-bit input records/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_input_records_total{name=~\"input_*\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "(App) Fluent-bit output process records/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_proc_records_total{name=\"output_geneva\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(App) Fluent-bit input bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_input_bytes_total{name=~\"input_*\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "(App) Fluent-bit output bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_proc_bytes_total{name=\"output_geneva\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(App) Fluent-bit output dropped records/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_dropped_records_total{name=~\"output_*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(App) Fluent-bit retries/fails",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_retries_failed_total{name=~\"output_*\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "(App) Fluent-bit error/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_errors_total{name=~\"output_*\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}