{
 "title": "Azure Monitor for Containers",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fluent-bit input records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_records_total{cluster=~\"$cluster\",name=~\"oms_tail\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input bytes/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_bytes_total{cluster=~\"$cluster\",name=~\"oms_tail\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output errors/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_errors_total{cluster=~\"$cluster\",name=~\"oms_output\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries failed errors/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 13 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_retries_failed_total{cluster=~\"$cluster\",name=~\"oms_output\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output dropped records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_dropped_records_total{cluster=~\"$cluster\", name=~\"oms_output\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input files opened/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 23 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_files_opened_total{cluster=~\"$cluster\",name=~\"oms_tail\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input files closed/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_files_closed_total{cluster=~\"$cluster\",name=~\"oms_tail\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit rotated files/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 36 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_files_rotated_total{cluster=~\"$cluster\",name=~\"oms_tail\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}