# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: none

variables:
  armServiceConnectionName: 'ai-acr-validation-rsx'
  subscription: '66010356-d8a5-42d3-8593-6aaa3aeb1c11'
  containerRegistry: 'aicommon' # this build pushes the aidev image to the dev ACR (caution: ACR that has "prod" in its name is the dev one, the one without "prod" is prod AME)
  repoImageName: '${{ variables.containerRegistry }}.azurecr.io/public/azuremonitor/applicationinsights/aidev'
  IS_PR: $[eq(variables['Build.Reason'], 'PullRequest')]

jobs:
- job: common
  variables:
    Codeql.SkipTaskAutoInjection: true
  pool:
    name: rambhatt-test-es-pool
  steps:
  - checkout: self
    fetchDepth: 0
    fetchTags: true
  - task: ComponentGovernanceComponentDetection@0
  ## dev builds are in format Major.Minor.Patch-CommitAheadCount-CommitId
  ## prod release are in format Major.Minor.Patch
  ## preview release are in format preview-Major.Minor.Patch
  - bash: |
      commit=$(git describe --tags)
      imageTag="$commit"
            
      echo "imageTag is $imageTag"
      
      echo "##vso[task.setvariable variable=imageTag;isOutput=true]$imageTag"
      
      cd $(Build.SourcesDirectory)/deployment/mergebranch-webhook-deployment/ServiceGroupRoot/Scripts
    name: setup

- job: build_linux
  timeoutInMinutes: 120
  dependsOn: common
  pool:
    name: rambhatt-test-es-pool
  variables:
    imageTag: $[ dependencies.common.outputs['setup.imageTag'] ]
    fullImageName: ${{ variables.repoImageName }}:$(imageTag)-test
    javaTestAppImageName: 'rambhattacr.azurecr.io/demoaks-java-app:latest'
    dotnetTestAppImageName: 'rambhattacr.azurecr.io/demoaks-dotnet-app:latest'
    nodeTestAppImageName: 'rambhattacr.azurecr.io/demoaks-nodejs-app:latest'
    testNamespace: 'test-ns'
    aiConnectionString: 'InstrumentationKey=910190fd-f49a-48e3-b6ac-6f0df84ceb5e;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/'
    Codeql.Enabled: true
    Codeql.BuildIdentifier: 'linuxbuild'
    # This is necessary because of: https://github.com/moby/moby/issues/37965
    DOCKER_BUILDKIT: 1

  steps:
  - task: CodeQL3000Init@0
  - task: AzureCLI@2
    displayName: "Ready Image and push to ACR"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        mkdir -p $(Build.ArtifactStagingDirectory)/linux

        echo "Installing NPM..."
        sudo apt-get -y install npm

        echo "Switching the directory..."
        cd appmonitoring/ts/src
        pwd
        ls -a
        
        echo "Installing npm packages..."
        sudo npm install

        #echo "Updating packages..."
        #npm update
        
        echo "Building the typescript project..."
        tsc --build --force
        
        if [ $? -ne 0 ]
        then
          echo "Build failed"
          exit 1
        fi

        echo "Build is done"

        echo "Running ESLint..."
        npx eslint .

        if [ $? -ne 0 ]
        then
          echo "ESLint failed"
          exit 1
        fi

        echo "ESLint is done"

        echo "Running Jest..."
        npm test

        if [ $? -ne 0 ]
        then
          echo "Jest failed"
          exit 1
        fi

        echo "Jest is done"
        
        pwd
        ls -a
        
        sudo apt-get update && sudo apt-get -y install qemu binfmt-support qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        docker buildx create --name testbuilder
        docker buildx use testbuilder

        az --version
        az account show
        az account set -s ${{ variables.subscription }}
        az acr login -n ${{ variables.containerRegistry }}

        echo "Build reason = $(Build.Reason)"

        echo ${{ variables.fullImageName }}
        
        docker buildx build --platform linux/amd64,linux/arm64 --tag ${{ variables.fullImageName }} -f ./Dockerfile --metadata-file $(Build.ArtifactStagingDirectory)/linux/metadata.json --push --provenance=false .
        docker pull ${{ variables.fullImageName }}

  - task: AzureCLI@2
    displayName: "Create deployment in AKS"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/helm
        pwd
        az account set --subscription 5a3b3ba4-3a42-42ae-b2cb-f882345803bc
        az aks get-credentials --resource-group aks-appmonitoring-pipeline --name aks-pipeline-validation-ai
        kubectl delete -f appmonitoring-deployment.yaml

        echo "Wait for 10s for everything to clear up..."
        sleep 10

        export AIDEV_IMAGE_NAME=${{ variables.fullImageName }}
        cat appmonitoring-deployment.yaml | envsubst | kubectl apply -f -

        echo "Wait for 10s for charts to be applied..."
        sleep 10

  - task: AzureCLI@2
    displayName: "Validate charts deployed to AKS"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/scripts
        pwd
        az account set --subscription 5a3b3ba4-3a42-42ae-b2cb-f882345803bc
        az aks get-credentials --resource-group aks-appmonitoring-pipeline --name aks-pipeline-validation-ai

        sudo chmod u+x ./validate-aks-charts.sh
        sudo chmod u+x ./validate-certs.sh

        echo "Checking for charts..."
        ./validate-aks-charts.sh
        
        echo "Checking for certificate installation..."
        ./validate-certs.sh

  # - task: AzureResourceManagerTemplateDeployment@3
  #   inputs:
  #     deploymentScope: 'Resource Group'
  #     azureResourceManagerConnection: 'ai-acr-validation-rsx'
  #     subscriptionId: '5a3b3ba4-3a42-42ae-b2cb-f882345803bc'
  #     action: 'Create Or Update Resource Group'
  #     resourceGroupName: 'aks-appmonitoring-pipeline'
  #     location: 'East US'
  #     templateLocation: 'Linked artifact'
  #     csmFile: '/path/to/here'
  #     deploymentMode: 'Incremental'

  - task: AzureCLI@2
    displayName: "Install CR and test apps"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/helm
        pwd
        az account set --subscription 5a3b3ba4-3a42-42ae-b2cb-f882345803bc
        az aks get-credentials --resource-group aks-appmonitoring-pipeline --name aks-pipeline-validation-ai
        kubectl delete -f java-test-app.yaml
        kubectl delete -f dotnet-test-app.yaml
        kubectl delete -f node-test-app.yaml
        kubectl delete -f appmonitoring-cr.yaml

        echo "Wait for 10s for everything to clear up..."
        sleep 10

        export JAVA_TEST_IMAGE_NAME=${{ variables.javaTestAppImageName }}
        export DOTNET_TEST_IMAGE_NAME=${{ variables.dotnetTestAppImageName }}
        export NODEJS_TEST_IMAGE_NAME=${{ variables.nodeTestAppImageName }}
        export TEST_NS="${{ variables.testNamespace }}"
        export AI_CONNECTION_STRING="${{ variables.aiConnectionString }}"

        kubectl create namespace $TEST_NS

        cat appmonitoring-cr.yaml | envsubst | kubectl apply -f -
        echo "Wait for 10s for CR to be applied and picked up..."
        sleep 10

        cat java-test-app.yaml | envsubst | kubectl apply -f -
        cat dotnet-test-app.yaml | envsubst | kubectl apply -f -
        cat node-test-app.yaml | envsubst | kubectl apply -f -

        echo "Wait for 10s for charts to be applied..."
        sleep 10

  - task: AzureCLI@2
    displayName: "Check test apps were mutated correctly"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/scripts
        pwd
        az account set --subscription 5a3b3ba4-3a42-42ae-b2cb-f882345803bc
        az aks get-credentials --resource-group aks-appmonitoring-pipeline --name aks-pipeline-validation-ai
        
        sudo chmod u+x ./validate-mutation.sh
        ./validate-mutation.sh "dotnet-test-app" "java-test-app" "nodejs-test-app" "test-ns"


