# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - ai_prod

pr:
  branches:
    include:
    - ai_prod

variables:
  armServiceConnectionName: 'ai-acr-validation-rsx'
  subscription: '66010356-d8a5-42d3-8593-6aaa3aeb1c11'
  containerRegistry: 'aicommon' # this build pushes the aidev image to the dev ACR (caution: ACR that has "prod" in its name is the dev one, the one without "prod" is prod AME)
  repoImageName: '${{ variables.containerRegistry }}.azurecr.io/public/azuremonitor/applicationinsights/aidev'
  IS_PR: $[eq(variables['Build.Reason'], 'PullRequest')]

jobs:
- job: common
  variables:
    Codeql.SkipTaskAutoInjection: true
  pool:
    name: rambhatt-test-es-pool
  steps:
  - checkout: self
    fetchDepth: 0
    fetchTags: true
  - task: ComponentGovernanceComponentDetection@0
  ## dev builds are in format Major.Minor.Patch-CommitAheadCount-CommitId
  ## prod release are in format Major.Minor.Patch
  ## preview release are in format preview-Major.Minor.Patch
  - bash: |
      commit=$(git describe --tags)
      imageTag="$commit"
            
      echo "imageTag is $imageTag"
      
      echo "##vso[task.setvariable variable=imageTag;isOutput=true]$imageTag"
      
      cd $(Build.SourcesDirectory)/deployment/mergebranch-webhook-deployment/ServiceGroupRoot/Scripts
    name: setup

- job: build_linux
  timeoutInMinutes: 120
  dependsOn: common
  pool:
    name: rambhatt-test-es-pool
  variables:
    imageTag: $[ dependencies.common.outputs['setup.imageTag'] ]
    fullImageName: 'placeholder'
    Codeql.Enabled: true
    Codeql.BuildIdentifier: 'linuxbuild'
    # This is necessary because of: https://github.com/moby/moby/issues/37965
    DOCKER_BUILDKIT: 1

  steps:
  - task: CodeQL3000Init@0
  - task: AzureCLI@2
    displayName: "Ready Image and push to ACR"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        mkdir -p $(Build.ArtifactStagingDirectory)/linux

        echo "Installing NPM..."
        sudo apt-get -y install npm

        echo "Switching the directory..."
        cd appmonitoring/ts/src
        pwd
        ls -a
        
        echo "Installing npm packages..."
        sudo npm install

        #echo "Updating packages..."
        #npm update
        
        echo "Building the typescript project..."
        tsc --build --force
        
        if [ $? -ne 0 ]
        then
          echo "Build failed"
          exit 1
        fi

        echo "Build is done"

        echo "Running ESLint..."
        npx eslint .

        if [ $? -ne 0 ]
        then
          echo "ESLint failed"
          exit 1
        fi

        echo "ESLint is done"

        echo "Running Jest..."
        npm test

        if [ $? -ne 0 ]
        then
          echo "Jest failed"
          exit 1
        fi

        echo "Jest is done"
        
        pwd
        ls -a
        
        sudo apt-get update && sudo apt-get -y install qemu binfmt-support qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        docker buildx create --name testbuilder
        docker buildx use testbuilder

        az --version
        az account show
        az account set -s ${{ variables.subscription }}
        az acr login -n ${{ variables.containerRegistry }}

        echo "Build reason = $(Build.Reason)"
        echo "##vso[task.setvariable variable=fullImageName;isOutput=true]${{ variables.repoImageName }}:$(imageTag)-test"

        targetRepoImage=${{ variables.repoImageName }}:$(imageTag)-test
        echo $targetRepoImage
        
        docker buildx build --platform linux/amd64,linux/arm64 --tag ${{ variables.fullImageName }} -f ./Dockerfile --metadata-file $(Build.ArtifactStagingDirectory)/linux/metadata.json --push --provenance=false .
        docker pull ${{ variables.fullImageName }}

  - task: AzureCLI@2
    displayName: "Create deployment in AKS"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az account set --subscription 66010356-d8a5-42d3-8593-6aaa3aeb1c11
        az aks get-credentials --resource-group appmonitoring-pipeline-test --name aks-pipeline-testbed-ai
        kubectl delete -f ../../helm/appmonitoring-deployment.yaml

        export AIDEV_IMAGE_NAME=${{ variables.fullImageName }}
        cat ../../helm/appmonitoring-deployment.yaml | envsubst | kubectl apply -f -
